# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

workspace:
  clean: all

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'

  # - task: DotNetCoreCLI@2
  #   inputs:
  #     command: 'restore'
  #     projects: '**/*.csproj'
  #     feedsToUse: 'select'
  #     vstsFeed: '1268a989-cd48-4170-99de-66c576a8bf1e/773fbe51-e6b4-4d87-90da-996c1a3cb1d5'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      projects: '**/*.csproj'
      custom: 'pack'
      arguments: '--version-suffix "alpha" -c Release'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '1268a989-cd48-4170-99de-66c576a8bf1e/773fbe51-e6b4-4d87-90da-996c1a3cb1d5'

