//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kastra.Core.Modules {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Kastra.Core.Modules.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        internal static string CompilationFailed {
            get {
                return ResourceManager.GetString("CompilationFailed", resourceCulture);
            }
        }
        
        internal static string FlushPointCannotBeInvoked {
            get {
                return ResourceManager.GetString("FlushPointCannotBeInvoked", resourceCulture);
            }
        }
        
        internal static string LayoutCannotBeLocated {
            get {
                return ResourceManager.GetString("LayoutCannotBeLocated", resourceCulture);
            }
        }
        
        internal static string LayoutCannotBeRendered {
            get {
                return ResourceManager.GetString("LayoutCannotBeRendered", resourceCulture);
            }
        }
        
        internal static string RazorPage_ThereIsNoActiveWritingScopeToEnd {
            get {
                return ResourceManager.GetString("RazorPage_ThereIsNoActiveWritingScopeToEnd", resourceCulture);
            }
        }
        
        internal static string RazorPage_CannotFlushWhileInAWritingScope {
            get {
                return ResourceManager.GetString("RazorPage_CannotFlushWhileInAWritingScope", resourceCulture);
            }
        }
        
        internal static string RazorPage_MethodCannotBeCalled {
            get {
                return ResourceManager.GetString("RazorPage_MethodCannotBeCalled", resourceCulture);
            }
        }
        
        internal static string RenderBodyNotCalled {
            get {
                return ResourceManager.GetString("RenderBodyNotCalled", resourceCulture);
            }
        }
        
        internal static string SectionAlreadyDefined {
            get {
                return ResourceManager.GetString("SectionAlreadyDefined", resourceCulture);
            }
        }
        
        internal static string SectionAlreadyRendered {
            get {
                return ResourceManager.GetString("SectionAlreadyRendered", resourceCulture);
            }
        }
        
        internal static string SectionNotDefined {
            get {
                return ResourceManager.GetString("SectionNotDefined", resourceCulture);
            }
        }
        
        internal static string SectionsNotRendered {
            get {
                return ResourceManager.GetString("SectionsNotRendered", resourceCulture);
            }
        }
        
        internal static string ViewContextMustBeSet {
            get {
                return ResourceManager.GetString("ViewContextMustBeSet", resourceCulture);
            }
        }
        
        internal static string GeneratedCodeFileName {
            get {
                return ResourceManager.GetString("GeneratedCodeFileName", resourceCulture);
            }
        }
        
        internal static string RazorPage_InvalidTagHelperIndexerAssignment {
            get {
                return ResourceManager.GetString("RazorPage_InvalidTagHelperIndexerAssignment", resourceCulture);
            }
        }
        
        internal static string CouldNotResolveApplicationRelativeUrl_TagHelper {
            get {
                return ResourceManager.GetString("CouldNotResolveApplicationRelativeUrl_TagHelper", resourceCulture);
            }
        }
        
        internal static string LayoutHasCircularReference {
            get {
                return ResourceManager.GetString("LayoutHasCircularReference", resourceCulture);
            }
        }
        
        internal static string Compilation_MissingReferences {
            get {
                return ResourceManager.GetString("Compilation_MissingReferences", resourceCulture);
            }
        }
        
        internal static string ViewLocationFormatsIsRequired {
            get {
                return ResourceManager.GetString("ViewLocationFormatsIsRequired", resourceCulture);
            }
        }
        
        internal static string RazorPage_NestingAttributeWritingScopesNotSupported {
            get {
                return ResourceManager.GetString("RazorPage_NestingAttributeWritingScopesNotSupported", resourceCulture);
            }
        }
        
        internal static string FileProvidersAreRequired {
            get {
                return ResourceManager.GetString("FileProvidersAreRequired", resourceCulture);
            }
        }
        
        internal static string RazorProject_PathMustStartWithForwardSlash {
            get {
                return ResourceManager.GetString("RazorProject_PathMustStartWithForwardSlash", resourceCulture);
            }
        }
        
        internal static string PropertyMustBeSet {
            get {
                return ResourceManager.GetString("PropertyMustBeSet", resourceCulture);
            }
        }
        
        internal static string RazorViewCompiler_ViewPathsDifferOnlyInCase {
            get {
                return ResourceManager.GetString("RazorViewCompiler_ViewPathsDifferOnlyInCase", resourceCulture);
            }
        }
        
        internal static string UnsupportedDebugInformationFormat {
            get {
                return ResourceManager.GetString("UnsupportedDebugInformationFormat", resourceCulture);
            }
        }
        
        internal static string CompiledViewDescriptor_NoData {
            get {
                return ResourceManager.GetString("CompiledViewDescriptor_NoData", resourceCulture);
            }
        }
    }
}
